/**
 * CV PDF generator using jsPDF.
 *
 * Generates polished PDF documents from CVData in 3 formats:
 * - full: Complete CV with all sections, multi-page
 * - resume: Top 3 jobs, top 2 education, top 5 certs, skills, languages (2-page target)
 * - summary: Brief bio, current role, education summary, skills (1-page target)
 *
 * Ported from personal site generator and adapted for SECiD CVData type.
 * Uses dynamic import of jsPDF to avoid SSR issues in Astro.
 */
import type { CVData } from '@/types/cv';

export type PdfFormat = 'full' | 'resume' | 'summary';

interface Labels {
  summary: string;
  experience: string;
  education: string;
  skills: string;
  certifications: string;
  languages: string;
  projects: string;
  present: string;
  page: string;
  generated: string;
}

const LABELS_ES: Labels = {
  summary: 'Resumen Profesional',
  experience: 'Experiencia Profesional',
  education: 'Educacion',
  skills: 'Habilidades Tecnicas',
  certifications: 'Certificaciones',
  languages: 'Idiomas',
  projects: 'Proyectos Destacados',
  present: 'Actual',
  page: 'Pagina',
  generated: 'Generado por SECiD — secid.mx',
};

const LABELS_EN: Labels = {
  summary: 'Professional Summary',
  experience: 'Professional Experience',
  education: 'Education',
  skills: 'Technical Skills',
  certifications: 'Certifications & Training',
  languages: 'Languages',
  projects: 'Selected Projects',
  present: 'Present',
  page: 'Page',
  generated: 'Generated by SECiD — secid.mx',
};

function getLabels(lang: 'es' | 'en'): Labels {
  return lang === 'es' ? LABELS_ES : LABELS_EN;
}

function hexToRgb(hex: string): [number, number, number] {
  const cleaned = hex.replace('#', '');
  const r = parseInt(cleaned.substring(0, 2), 16);
  const g = parseInt(cleaned.substring(2, 4), 16);
  const b = parseInt(cleaned.substring(4, 6), 16);
  if (isNaN(r) || isNaN(g) || isNaN(b)) {
    return [30, 58, 95]; // fallback to SECiD blue
  }
  return [r, g, b];
}

function sanitizeText(t: string): string {
  if (!t) return '';
  let s = t
    .replace(/[\u2010-\u2015\u2212]/g, '-')
    .replace(/[⁻−]/g, '-')
    .replace(/[\u2000-\u200B\u00A0\u202F\u205F\u180E\u1680\u3000]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  try {
    s = s.normalize('NFKD');
  } catch {
    /* noop */
  }
  s = s.replace(/[^\x20-\x7E]/g, '');
  s = s
    .split(/ {2,}/)
    .map((chunk) => {
      if (/^(?:[A-Za-z] ){2,}[A-Za-z]$/.test(chunk)) return chunk.replace(/ /g, '');
      return chunk;
    })
    .join(' ');
  return s;
}

function fixSpacedOutParagraph(p: string): string {
  const ratio = (p.match(/\b\w\b/g) || []).length / (p.split(/\s+/).length || 1);
  if (/(?:[A-Za-z]\s){15,}[A-Za-z]/.test(p) || ratio > 0.65) {
    return p.replace(/([A-Za-z])\s(?=[A-Za-z])/g, '$1');
  }
  return p;
}

function formatDate(dateStr: string | undefined | null, presentLabel: string): string {
  if (!dateStr) return presentLabel;
  if (dateStr.includes('-')) {
    const parts = dateStr.split('-');
    const year = parts[0] ?? '';
    const month = parts[1] ?? '';
    const monthNames = [
      '',
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    const monthIndex = parseInt(month, 10);
    if (monthIndex >= 1 && monthIndex <= 12) {
      return `${monthNames[monthIndex]} ${year}`;
    }
    return year;
  }
  return dateStr;
}

function buildFilename(firstName: string, lastName: string, format: PdfFormat): string {
  const formatLabel =
    format === 'full' ? 'CV_Full' : format === 'resume' ? 'Resume_2pg' : 'Resume_1pg';
  return `${firstName}_${lastName}_${formatLabel}.pdf`;
}

function getExperienceSlice(format: PdfFormat, total: number): number {
  if (format === 'summary') return Math.min(2, total);
  if (format === 'resume') return Math.min(3, total);
  return total;
}

function getEducationSlice(format: PdfFormat, total: number): number {
  if (format === 'summary') return Math.min(2, total);
  if (format === 'resume') return Math.min(2, total);
  return total;
}

/**
 * Generate and download a PDF from CV data.
 *
 * Dynamically imports jsPDF to avoid SSR issues.
 * The generated PDF is automatically downloaded via `doc.save()`.
 */
export async function generateCvPdf(
  cvData: CVData,
  format: PdfFormat,
  lang: 'es' | 'en',
  accentColor: string = '#1E3A5F'
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF('p', 'mm', 'a4');

  const labels = getLabels(lang);
  const personal = cvData.personal;

  const pageWidth = 210;
  const pageHeight = 297;
  const leftMargin = 18;
  const rightMargin = 18;
  const topMargin = format === 'summary' ? 16 : 20;
  const bottomMargin = 20;
  const contentWidth = pageWidth - leftMargin - rightMargin;

  let yPos = topMargin;

  const accent: [number, number, number] = hexToRgb(accentColor);
  const darkGray: [number, number, number] = [40, 40, 40];
  const gray: [number, number, number] = [105, 105, 105];
  const lightGray: [number, number, number] = [200, 200, 200];

  const lineHeight = format === 'summary' ? 4.5 : 5;
  const bulletIndent = 4;
  const sectionSpacing = format === 'summary' ? 4 : 6;
  const bulletGap = format === 'summary' ? 1.5 : 2;

  pdf.setFont('helvetica', 'normal');

  // --- Helper functions ---

  function wrapText(text: string, maxWidth: number, fontSize: number): string[] {
    pdf.setFontSize(fontSize);
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = '';
    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      if (pdf.getTextWidth(testLine) > maxWidth && currentLine) {
        lines.push(currentLine);
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    }
    if (currentLine) lines.push(currentLine);
    return lines;
  }

  function renderWrappedText(
    text: string,
    x: number,
    y: number,
    maxWidth: number,
    fontSize: number,
    lineHt: number
  ): number {
    const lines = wrapText(sanitizeText(text), maxWidth, fontSize);
    pdf.setFontSize(fontSize);
    lines.forEach((line, index) => pdf.text(line, x, y + index * lineHt));
    return lines.length * lineHt;
  }

  function drawRunningHeader(): void {
    const firstName = personal.name.first.split(' ')[0];
    const lastName = personal.name.last.split(' ')[0];
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(...accent);
    pdf.text(`${firstName} ${lastName}`, leftMargin, topMargin - 6);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(...gray);
    const headerRight = [
      personal.title,
      personal.contact.email,
    ]
      .filter(Boolean)
      .join('  •  ');
    pdf.text(headerRight, pageWidth - rightMargin, topMargin - 6, { align: 'right' });
    pdf.setDrawColor(...lightGray);
    pdf.setLineWidth(0.3);
    pdf.line(leftMargin, topMargin - 4, pageWidth - rightMargin, topMargin - 4);
  }

  function checkPageBreak(requiredSpace: number, reflowHeader = true): boolean {
    if (yPos + requiredSpace > pageHeight - bottomMargin) {
      pdf.addPage();
      yPos = topMargin;
      if (reflowHeader) drawRunningHeader();
      return true;
    }
    return false;
  }

  function addSectionHeader(title: string): void {
    if (format === 'summary') yPos += 1;
    checkPageBreak(15);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(format === 'summary' ? 11 : 11.5);
    pdf.setTextColor(...accent);
    pdf.text(title.toUpperCase(), leftMargin, yPos);
    pdf.setDrawColor(...accent);
    pdf.setLineWidth(format === 'summary' ? 0.5 : 0.7);
    const underlineWidth = format === 'summary' ? 50 : 60;
    pdf.line(leftMargin, yPos + 1.8, leftMargin + underlineWidth, yPos + 1.8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...darkGray);
    yPos += format === 'summary' ? 6 : 8;
  }

  function drawBullet(baselineY: number, fontSize: number): void {
    const r = 1.08;
    pdf.setFillColor(...accent);
    const centerY = baselineY - fontSize * 0.14;
    pdf.circle(leftMargin + 1.8, centerY, r, 'F');
  }

  function renderBulletParagraph(text: string, fontSize = 9): void {
    const clean = sanitizeText(text);
    const maxWidth = contentWidth - bulletIndent;
    const lines = wrapText(clean, maxWidth, fontSize);
    const requiredHeight = lines.length * (lineHeight - 0.2) + bulletGap + 1.5;
    if (yPos + requiredHeight > pageHeight - bottomMargin) {
      checkPageBreak(requiredHeight);
    }
    const baseline = yPos;
    drawBullet(baseline, fontSize);
    const xStart = leftMargin + bulletIndent;
    pdf.setFontSize(fontSize);
    pdf.setTextColor(...darkGray);
    lines.forEach((ln, idx) => {
      pdf.text(ln, xStart, baseline + idx * (lineHeight - 0.2));
    });
    yPos = baseline + lines.length * (lineHeight - 0.2) + bulletGap;
  }

  // ============ HEADER ============

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(format === 'summary' ? 18 : 20);
  pdf.setTextColor(...darkGray);
  pdf.text(sanitizeText(personal.name.full), leftMargin, yPos);
  yPos += format === 'summary' ? 6 : 9;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(format === 'summary' ? 11 : 12.5);
  pdf.setTextColor(...accent);
  pdf.text(sanitizeText(personal.title), leftMargin, yPos);
  yPos += format === 'summary' ? 5 : 7;

  if (format === 'summary' || format === 'resume') {
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(8);
    pdf.setTextColor(...gray);
    const pageCount = format === 'summary' ? '1' : '2';
    const subtitle =
      lang === 'es'
        ? `Resumen de ${pageCount} pagina — Generado por SECiD`
        : `${pageCount}-Page Resume Highlights — Generated by SECiD`;
    pdf.text(subtitle, leftMargin, yPos);
    yPos += 4;
  }

  // Contact line
  const contactParts = [
    personal.location,
    personal.contact.email,
    personal.contact.linkedin,
  ].filter(Boolean);
  pdf.setFontSize(format === 'summary' ? 8.5 : 9);
  pdf.setTextColor(...gray);
  pdf.text(sanitizeText(contactParts.join('  •  ')), leftMargin, yPos);
  yPos += format === 'summary' ? 6 : 10;

  // Divider
  pdf.setDrawColor(...lightGray);
  pdf.setLineWidth(0.3);
  pdf.line(leftMargin, yPos, pageWidth - rightMargin, yPos);
  yPos += format === 'summary' ? 4 : 6;

  // ============ PROFESSIONAL SUMMARY ============
  if (personal.summary) {
    addSectionHeader(labels.summary);
    const cleaned = fixSpacedOutParagraph(sanitizeText(personal.summary));
    const fontSize = format === 'summary' ? 8.5 : 9.1;
    const h = renderWrappedText(cleaned, leftMargin, yPos, contentWidth, fontSize, lineHeight - 0.3);
    yPos += h + (format === 'summary' ? 1 : 2);
    yPos += format === 'summary' ? 2 : sectionSpacing;
  }

  // ============ PROFESSIONAL EXPERIENCE ============
  const expSlice = getExperienceSlice(format, cvData.experience.length);
  const experiences = cvData.experience.slice(0, expSlice);

  if (experiences.length > 0) {
    addSectionHeader(labels.experience);

    experiences.forEach((job, jobIndex) => {
      checkPageBreak(40);

      // Job title
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10.5);
      pdf.setTextColor(...darkGray);
      pdf.text(sanitizeText(job.title), leftMargin, yPos);

      // Date range (right-aligned)
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(...gray);
      const endDateText = job.current
        ? labels.present
        : formatDate(job.endDate, labels.present);
      const dateText = `${formatDate(job.startDate, '')} - ${endDateText}`;
      pdf.text(dateText, pageWidth - rightMargin - pdf.getTextWidth(dateText), yPos);
      yPos += 4.5;

      // Company name in accent color
      pdf.setFont('helvetica', 'italic');
      pdf.setFontSize(9.5);
      pdf.setTextColor(...accent);
      const companyText = job.location
        ? `${job.company}, ${job.location}`
        : job.company;
      pdf.text(sanitizeText(companyText), leftMargin, yPos);
      yPos += 4.5;

      // Description as bullet point
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(...darkGray);

      if (job.description) {
        const bulletFontSize = format === 'summary' ? 8.5 : 8.9;
        let descText = job.description;
        if (format === 'summary' && jobIndex > 0 && descText.length > 120) {
          descText = descText.slice(0, 120) + '...';
        }
        renderBulletParagraph(descText, bulletFontSize);
      }

      // Technologies
      if (job.technologies && job.technologies.length > 0 && format !== 'summary') {
        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(8);
        pdf.setTextColor(...gray);
        const techText = job.technologies.join(', ');
        const techLines = wrapText(sanitizeText(techText), contentWidth - bulletIndent, 8);
        techLines.forEach((line, idx) => {
          pdf.text(line, leftMargin + bulletIndent, yPos + idx * (lineHeight - 0.5));
        });
        yPos += techLines.length * (lineHeight - 0.5) + 1;
        pdf.setFont('helvetica', 'normal');
      }

      yPos += 2;

      // Separator line between jobs
      pdf.setDrawColor(...lightGray);
      pdf.setLineWidth(0.2);
      pdf.line(leftMargin, yPos, pageWidth - rightMargin, yPos);
      yPos += 4;
    });
  }

  // ============ EDUCATION ============
  const eduSlice = getEducationSlice(format, cvData.education.length);
  const educationItems = cvData.education.slice(0, eduSlice);

  if (educationItems.length > 0) {
    checkPageBreak(40);
    addSectionHeader(labels.education);

    educationItems.forEach((edu) => {
      checkPageBreak(12);

      if (format === 'summary') {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(9);
        pdf.setTextColor(...darkGray);
        pdf.text(sanitizeText(edu.degree), leftMargin, yPos);
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(8);
        pdf.setTextColor(...gray);
        const endLabel = edu.current ? labels.present : formatDate(edu.endDate, labels.present);
        const eduDateText = `${formatDate(edu.startDate, '')} - ${endLabel}`;
        pdf.text(eduDateText, pageWidth - rightMargin - pdf.getTextWidth(eduDateText), yPos);
        yPos += 3.5;
        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(8);
        pdf.text(sanitizeText(edu.institution), leftMargin, yPos);
        yPos += 4;
      } else {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(11);
        pdf.setTextColor(...darkGray);
        pdf.text(sanitizeText(edu.degree), leftMargin, yPos);
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(9);
        pdf.setTextColor(...gray);
        const endLabel = edu.current ? labels.present : formatDate(edu.endDate, labels.present);
        const eduDateText = `${formatDate(edu.startDate, '')} - ${endLabel}`;
        pdf.text(eduDateText, pageWidth - rightMargin - pdf.getTextWidth(eduDateText), yPos);
        yPos += 5;
        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(10);
        pdf.text(sanitizeText(edu.institution), leftMargin, yPos);
        yPos += 5;
        if (edu.gpa) {
          pdf.setFont('helvetica', 'normal');
          pdf.setFontSize(9);
          pdf.setTextColor(...darkGray);
          pdf.text(`GPA: ${edu.gpa}`, leftMargin, yPos);
          yPos += 5;
        }
        if (edu.fieldOfStudy) {
          pdf.setFont('helvetica', 'normal');
          pdf.setFontSize(9);
          pdf.setTextColor(...gray);
          pdf.text(sanitizeText(edu.fieldOfStudy), leftMargin, yPos);
          yPos += 5;
        }
        yPos += 3;
      }
    });
  }

  // ============ TECHNICAL SKILLS (two-column layout) ============
  if (cvData.skills.length > 0) {
    checkPageBreak(40);
    addSectionHeader(labels.skills);

    const colGap = 10;
    const colWidth = (contentWidth - colGap) / 2;
    const leftX = leftMargin;
    const rightX = leftMargin + colWidth + colGap;

    // Split skills into two roughly equal columns
    const midpoint = Math.ceil(cvData.skills.length / 2);
    const leftSkills = cvData.skills.slice(0, midpoint);
    const rightSkills = cvData.skills.slice(midpoint);

    const skillFontSize = format === 'summary' ? 8 : 8.5;
    const skillLineHeight = format === 'summary' ? 3.5 : 4.2;

    let leftY = yPos;
    let rightY = yPos;

    // Left column
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(skillFontSize);
    pdf.setTextColor(...darkGray);
    const leftText = leftSkills.join(', ');
    const leftLines = wrapText(sanitizeText(leftText), colWidth, skillFontSize);
    leftLines.forEach((line, idx) => {
      pdf.text(line, leftX, leftY + idx * skillLineHeight);
    });
    leftY += leftLines.length * skillLineHeight;

    // Right column
    if (rightSkills.length > 0) {
      const rightText = rightSkills.join(', ');
      const rightLines = wrapText(sanitizeText(rightText), colWidth, skillFontSize);
      rightLines.forEach((line, idx) => {
        pdf.text(line, rightX, rightY + idx * skillLineHeight);
      });
      rightY += rightLines.length * skillLineHeight;
    }

    yPos = Math.max(leftY, rightY) + (format === 'summary' ? 4 : 6);
  }

  // ============ CERTIFICATIONS ============
  if (format !== 'summary' && cvData.certifications.length > 0) {
    checkPageBreak(40);
    addSectionHeader(labels.certifications);

    const certLimit = format === 'full' ? cvData.certifications.length : 5;
    const certs = cvData.certifications.slice(0, certLimit);

    certs.forEach((cert) => {
      checkPageBreak(10);
      const certText = `${cert.name} - ${cert.issuer} (${cert.date})`;
      renderBulletParagraph(certText, 9);
    });
    yPos += 4;
  }

  // ============ LANGUAGES ============
  if (cvData.languages.length > 0) {
    checkPageBreak(25);
    addSectionHeader(labels.languages);

    cvData.languages.forEach((lang) => {
      renderBulletParagraph(`${lang.name} (${lang.proficiency})`, 9);
    });
    yPos += 2;
  }

  // ============ PROJECTS (full only) ============
  if (format === 'full' && cvData.projects.length > 0) {
    checkPageBreak(50);
    addSectionHeader(labels.projects);

    cvData.projects.slice(0, 3).forEach((project) => {
      checkPageBreak(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10);
      pdf.setTextColor(...darkGray);

      const nameWidth = pdf.getTextWidth(project.title);
      const maxNameWidth = contentWidth - 25;
      let displayName = project.title;
      if (nameWidth > maxNameWidth) {
        let truncated = project.title;
        while (
          pdf.getTextWidth(truncated + '...') > maxNameWidth &&
          truncated.length > 4
        ) {
          truncated = truncated.slice(0, -1);
        }
        displayName = truncated + '...';
      }
      pdf.text(sanitizeText(displayName), leftMargin, yPos);
      pdf.setFont('helvetica', 'normal');
      yPos += 5;

      if (project.description) {
        const projH = renderWrappedText(
          project.description,
          leftMargin + 5,
          yPos,
          contentWidth - 10,
          9,
          5
        );
        yPos += projH + 3;
      }

      if (project.technologies.length > 0) {
        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(8);
        pdf.setTextColor(...gray);
        const techStr = project.technologies.join(', ');
        const techLines = wrapText(sanitizeText(techStr), contentWidth - 10, 8);
        techLines.forEach((line, idx) => {
          pdf.text(line, leftMargin + 5, yPos + idx * (lineHeight - 0.5));
        });
        yPos += techLines.length * (lineHeight - 0.5) + 3;
        pdf.setFont('helvetica', 'normal');
      }
    });
  }

  // ============ PAGE NUMBERS ============
  const totalPages = (pdf.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(9);
    pdf.setTextColor(...gray);

    if (
      (format === 'summary' && i === 1) ||
      (format === 'resume' && i === totalPages)
    ) {
      pdf.setFont('helvetica', 'italic');
      pdf.setFontSize(7.5);
      pdf.text(labels.generated, pageWidth / 2, pageHeight - 10, { align: 'center' });
    } else if (format !== 'summary') {
      pdf.text(
        `${labels.page} ${i} / ${totalPages}`,
        pageWidth / 2,
        pageHeight - 15,
        { align: 'center' }
      );
    }
  }

  // ============ DOCUMENT PROPERTIES ============
  pdf.setProperties({
    title: `${personal.name.full} - CV`,
    subject: 'Curriculum Vitae',
    author: personal.name.full,
    creator: 'SECiD CV Generator',
  });

  const filename = buildFilename(personal.name.first, personal.name.last, format);
  pdf.save(filename);
}
