import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';
import compress from 'astro-compress';
import node from '@astrojs/node';

// https://astro.build/config
export default defineConfig({
  site: 'https://secid.mx',
  base: process.env.NODE_ENV === 'production' ? '' : '/',

  // Hybrid mode: static by default, server-rendered for dynamic routes
  output: 'hybrid',
  adapter: node({
    mode: 'standalone',
  }),
  
  // Build configuration
  build: {
    format: 'directory',
    assets: 'assets',
  },
  
  // Integrations
  integrations: [
    react(),
    tailwind({
      applyBaseStyles: false,
      nesting: true,
    }),
    sitemap({
      i18n: {
        defaultLocale: 'es',
        locales: {
          es: 'es-MX',
          en: 'en-US',
        },
      },
    }),
    compress({
      CSS: true,
      HTML: {
        caseSensitive: true,
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        conservativeCollapse: false,
        decodeEntities: true,
        html5: true,
        ignoreCustomComments: [],
        ignoreCustomFragments: [],
        includeAutoGeneratedTags: false,
        keepClosingSlash: true,
        minifyCSS: true,
        minifyJS: true,
        preserveLineBreaks: false,
        preventAttributesEscaping: false,
        processConditionalComments: true,
        processScripts: ['application/ld+json'],
        quoteCharacter: '"',
        removeAttributeQuotes: false,
        removeComments: true,
        removeEmptyAttributes: true,
        removeEmptyElements: false,
        removeOptionalTags: false,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeTagWhitespace: false,
        sortAttributes: true,
        sortClassName: true,
        trimCustomFragments: true,
        useShortDoctype: true,
      },
      Image: false, // We'll handle image optimization separately
      JavaScript: true,
      SVG: true,
    }),
  ],
  
  // Vite configuration
  vite: {
    ssr: {
      external: ['firebase', 'firebase-admin'],
    },
    build: {
      rollupOptions: {
        external: ['sharp'],
      },
    },
    optimizeDeps: {
      exclude: ['firebase', 'firebase/app', 'firebase/auth', 'firebase/firestore', 'firebase/storage'],
    },
  },
  
  // i18n configuration
  i18n: {
    defaultLocale: 'es',
    locales: ['es', 'en'],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  
  // Markdown configuration
  markdown: {
    shikiConfig: {
      theme: 'github-dark',
      langs: ['js', 'ts', 'jsx', 'tsx', 'json', 'css', 'html', 'bash'],
      wrap: true,
    },
  },
  
  // Prefetch configuration for better performance
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'viewport',
  },
  
  // View transitions
  viewTransitions: true,
});